import React from "react";
import logo1 from "../../../public/scrollImage/agora.svg";
import logo2 from "../../../public/scrollImage/bluepillow-logo.svg";

import logo3 from "../../../public/scrollImage/ease-logo.svg";
import logo4 from "../../../public/scrollImage/goibibo.png";
import logo5 from "../../../public/scrollImage/logo-home.svg";
import logo6 from "../../../public/scrollImage/logoo.svg";

export default function BookingAlliance() {
  return (
    <>
      <div className="px-[10px] 2xl:w-[1400px] pb-[0px] my-[20px] items-center flex flex-col gap-[10px] w-[80%]  mx-auto">
     
        <h1 className="flex font-Poppins w-[100%]  items-center gap-[10px] pt-[10px] font-[500] text-[23px] mx-auto">
        <div className="h-[2px] bg-gradient-to-r w-[310px] from-transparent to-[#ff8000] flex-grow" />
          Booking Alliances
          <div className="h-[2px] bg-gradient-to-r from-[#FF6B00] to-transparent flex-grow w-[300px]" />
        </h1>
        <div className="relative mt-[40px]  w-full  overflow-hidden">
          {/* Sliding Container */}
          <div className="flex scroll-content w-fit gap-[60px]">
            {/* Duplicate logos for seamless effect */}
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />{" "}
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />{" "}
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />{" "}
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />{" "}
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
            <img className="w-[100px]" src={logo1} alt="Logo 1" />
            <img className="w-[100px]" src={logo2} alt="Logo 2" />
            <img className="w-[100px]" src={logo3} alt="Logo 3" />
            <img className="w-[100px]" src={logo4} alt="Logo 4" />
            <img className="w-[100px]" src={logo5} alt="Logo 5" />
            <img className="w-[100px]" src={logo6} alt="Logo 6" />
          </div>
        </div>
        <div className="w-[80%] mt-[65px] mx-auto h-[1px] bg-gradient-to-r from-transparent via-[#d8d8d8] to-transparent"></div>

      </div>
    </>
  );
}
